export type VerdantiaAsset = {
  src: `/assets/${string}`;
  width: number;
  height: number;
  aspect: "landscape" | "wide" | "portrait" | "square";
  alt: string;
  role: "decorative" | "informative";
  use: string;
  loading: "priority" | "lazy";
  crop: "full-bleed" | "center" | "object-left" | "object-right" | "contain";
  notes?: string;
};

export const verdantiaAssets = {
  homeHero: {
    src: "/assets/verdantia-hero-field-guide.webp",
    width: 1672,
    height: 941,
    aspect: "wide",
    alt: "",
    role: "decorative",
    use: "Homepage atmospheric field-guide backdrop; decorative only because all key copy is in the DOM.",
    loading: "priority",
    crop: "full-bleed",
    notes: "WebP replacement for the older 2.4MB PNG. Keep the PNG as source material until cleanup is approved.",
  },
  offerDecisionBoard: {
    src: "/assets/verdantia-offer-decision-board.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia offer decision board with route lanes on warm paper.",
    role: "informative",
    use: "Offers hub hero and decision-board support visual.",
    loading: "priority",
    crop: "center",
  },
  workshopFieldGuide: {
    src: "/assets/verdantia-workshop-field-guide.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Editorial field-guide workshop materials with paper cards and folders.",
    role: "informative",
    use: "Practical AI Workshop hero/support visual.",
    loading: "priority",
    crop: "center",
  },
  resourceLibraryWall: {
    src: "/assets/verdantia-resource-library-wall.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia resource library materials and checklist cards on warm paper.",
    role: "informative",
    use: "Resources route hero/support visual.",
    loading: "priority",
    crop: "center",
  },
  learningLab: {
    src: "/assets/verdantia-learning-lab.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia learning-lab workbench with notebooks and route lines.",
    role: "informative",
    use: "Learning route hero/support visual.",
    loading: "priority",
    crop: "center",
  },
  resourceMaterials: {
    src: "/assets/verdantia-resource-materials.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia product and resource materials on warm paper.",
    role: "informative",
    use: "Products/resources support visual.",
    loading: "lazy",
    crop: "center",
  },
  companyDesk: {
    src: "/assets/verdantia-company-desk.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia founder-led practice desk with papers and route lines.",
    role: "informative",
    use: "Company route support visual.",
    loading: "priority",
    crop: "center",
  },
  enquiryWorkspace: {
    src: "/assets/verdantia-enquiry-workspace.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia enquiry workspace with a blank contact brief and paper stack.",
    role: "informative",
    use: "Contact route support visual.",
    loading: "priority",
    crop: "center",
  },
  pathfinderMap: {
    src: "/assets/verdantia-pathfinder-map.webp",
    width: 1600,
    height: 900,
    aspect: "wide",
    alt: "Abstract Verdantia Pathfinder map with route lines and paper materials.",
    role: "informative",
    use: "Pathfinder route support visual.",
    loading: "priority",
    crop: "center",
  },
  teamBriefingHero: {
    src: "/assets/verdantia-offer-team-briefing-hero.webp",
    width: 1586,
    height: 992,
    aspect: "landscape",
    alt: "Editorial briefing table with blank paper cards, evergreen accents, and route markers.",
    role: "informative",
    use: "AI Team Briefing offer detail hero.",
    loading: "priority",
    crop: "center",
  },
  adoptionDayMap: {
    src: "/assets/verdantia-offer-adoption-day-map.webp",
    width: 1586,
    height: 992,
    aspect: "landscape",
    alt: "Editorial adoption-day workflow map with paper cards and route markers.",
    role: "informative",
    use: "AI Adoption Day offer detail hero.",
    loading: "priority",
    crop: "center",
  },
  adoptionSprintRhythm: {
    src: "/assets/verdantia-offer-adoption-sprint-rhythm.webp",
    width: 1586,
    height: 992,
    aspect: "landscape",
    alt: "Editorial adoption sprint rhythm board with roadmap cards and review markers.",
    role: "informative",
    use: "AI Adoption Sprint offer detail hero.",
    loading: "priority",
    crop: "center",
  },
  videoSocialAdsStoryboard: {
    src: "/assets/verdantia-offer-video-social-ads-storyboard.webp",
    width: 1586,
    height: 992,
    aspect: "landscape",
    alt: "Editorial AI video and social ads storyboard with hook cards and caption notes.",
    role: "informative",
    use: "AI Video Creation and Social Ads offer detail hero.",
    loading: "priority",
    crop: "center",
  },
  founderPortrait: {
    src: "/assets/gbemi-akadiri.webp",
    width: 900,
    height: 900,
    aspect: "square",
    alt: "Gbemi Akadiri, founder of Verdantia.",
    role: "informative",
    use: "Founder credibility section.",
    loading: "lazy",
    crop: "center",
  },
} as const satisfies Record<string, VerdantiaAsset>;

export type VerdantiaAssetKey = keyof typeof verdantiaAssets;

export const routeHeroAssetKeys = {
  offers: "offerDecisionBoard",
  workshop: "workshopFieldGuide",
  resources: "resourceLibraryWall",
  learning: "learningLab",
  products: "resourceMaterials",
  company: "companyDesk",
  contact: "enquiryWorkspace",
  pathfinder: "pathfinderMap",
} as const satisfies Record<string, VerdantiaAssetKey>;
